package com.att.android.speech;

public enum C0120e {
    USER_CANCELED,
    PARAMETER_ERROR,
    CAPTURE_FAILED,
    BELOW_MINIMUM_LENGTH,
    INAUDIBLE,
    CONNECTION_ERROR,
    RESPONSE_ERROR,
    SERVER_ERROR,
    OTHER_ERROR
}
